[package]
name = "memmem"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.5"
memchr = "2.5.0"

[profile.bench]
codegen-units = 1
lto = "thin"

[[bench]]
name = "bench"
harness = false
